simple_edu/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

static_url = static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
media_url = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('tasks.urls'))
] + static_url + media_url

tasks/urls.py
from django.conf.urls import url

from .views import TaskListView, TaskCreateView, CheckCodeView, TestCodeView, \
    TaskDeleteView

app_name = "tasks"

urlpatterns = [
    url(r'^$', TaskListView.as_view(), name='list'),
    url(r'^new$', TaskCreateView.as_view(), name='new'),
    url(r'^check$', CheckCodeView.as_view(), name='check'),
    url(r'^test$', TestCodeView.as_view(), name='test'),
    url(r'^delete$', TaskDeleteView.as_view(), name='delete'),
]

tasks/models.py
import inspect
from enum import Enum
from django.db import models


class ChoiceEnum(Enum):

    @classmethod
    def choices(cls):
        # get all members of the class
        members = inspect.getmembers(cls, lambda m: not(inspect.isroutine(m)))
        # filter down to just properties
        props = [m for m in members if not(m[0][:2] == '__')]
        # format into django choice tuple
        choices = tuple([(str(p[1].value), p[0]) for p in props])
        return choices


class StatusEnum(ChoiceEnum):
    not_tested = 0
    tested = 1
    on_review = 2
    done = 3


class Task(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    file = models.FileField(null=True)
    status = models.CharField(max_length=1, choices=StatusEnum.choices(),
                              default=StatusEnum.not_tested.value)


class TestCase(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    file = models.FileField(blank=True, null=True)
    task = models.ForeignKey(
        Task, verbose_name='Тесты для задач', related_name='cases',
        on_delete=models.CASCADE)

    def get_input_items(self):
        return self.items.filter(is_input=True)

    def get_output_items(self):
        return self.items.filter(is_input=False)


class TestInOut(models.Model):
    value = models.CharField(max_length=255)
    test_case = models.ForeignKey(TestCase, on_delete=models.CASCADE,
                                  verbose_name='Входные/выходные данные',
                                  related_name='items')
    is_input = models.BooleanField(default=True)

tasks/forms.py
from django.forms import ModelForm

from .models import Task


class UploadFileForm(ModelForm):

    class Meta:
        model = Task
        fields = ['title', 'description', 'file']

tasks/views.py
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import FormView, View
from django.http import HttpResponseRedirect, JsonResponse

from .models import Task
from .forms import UploadFileForm
from .utils import check_code, test_code


class TaskCreateView(FormView):
    form_class = UploadFileForm
    template_name = 'tasks/task_new.html'
    success_url = reverse_lazy('tasks:list')

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse_lazy('tasks:list'))
        else:
            return self.form_invalid(form)


class TaskListView(ListView):
    model = Task


class CheckCodeView(View):

    def post(self, request, *args, **kwargs):
        task_id = request.POST['task_id']
        try:
            task = Task.objects.get(id=task_id)
        except Task.DoesNotExist:
            errors = []
            valid = False
        else:
            errors, valid = check_code(task.file.path)
        return JsonResponse(
            {'errors': errors, 'valid': valid})


class TestCodeView(View):

    def post(self, request, *args, **kwargs):
        task_id = request.POST['task_id']
        errors, valid = test_code(task_id)
        return JsonResponse({'errors': errors, 'valid': valid})


class TaskDeleteView(View):

    def post(self, request, *args, **kwargs):
        task_id = request.POST['task_id']
        Task.objects.filter(id=task_id).delete()
        return JsonResponse({'errors': [], 'valid': True})

tasks/templates/tasks/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Education</title>

    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
          integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb"
          crossorigin="anonymous">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="http://example.com"
                   id="dropdown01" data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false">Dropdown</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search"
                   aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
                Search
            </button>
        </form>
    </div>
</nav>

<main role="main">
    <div class="jumbotron">
        <p>
            <a class="btn btn-primary btn-lg"
               href="{% url 'tasks:new' %}" role="button">Добавить новый код</a>
        </p>

    </div>
    <div class="container">
        <div class="messages">
        </div>
        <div class="row">
            {% block tasks %}{% endblock %}
        </div>
    </div> <!-- /container -->

</main>

<footer class="container">
</footer>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
        integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"
        integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
        crossorigin="anonymous"></script>
<script src="{% static 'js/task_js.js' %}"></script>
{% block extra_js %}{% endblock %}
</body>
</html>

tasks/templates/tasks/task_list.html
{% extends 'tasks/base.html' %}


{% load static %}


{% block tasks %}
    {% for task in object_list %}
        <div class="col-md-4">
            <h2>{{ task.title }}</h2>
            <p>{{ task.description }}</p>
            <p><a class="btn btn-primary btn-lg js_submit_order"
                  href="#" role="button"
                  data-id="{{ task.id }}"
                  data-url="{% url 'tasks:check' %}">Проверить код</a></p>
            <p><a class="btn btn-primary btn-lg js_submit_order"
                  href="#" role="button"
                  data-id="{{ task.id }}"
                  data-url="{% url 'tasks:test' %}">Протестировать код</a></p>
            <p><a class="btn btn-primary btn-lg js_submit_order"
                  href="#" role="button"
                  data-id="{{ task.id }}"
                  data-url="{% url 'tasks:delete' %}">Удалить</a></p>
        </div>
    {% endfor %}
{% endblock %}

tasks/templates/tasks/task_new.html
{% extends 'tasks/base.html' %}


{% load static %}


{% block tasks %}
    <div class="container">
            <form action="{% url 'tasks:new' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form }}
                <input type="submit">
            </form>
        </div>
{% endblock %}